!!python/object/apply:collections.OrderedDict
- - - env_wrapper
    - sb3_contrib.common.wrappers.TimeFeatureWrapper
  - - n_timesteps
    - 1000000.0
  - - normalize
    - true
  - - policy
    - MlpPolicy
