!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 128
  - - buffer_size
    - 50000
  - - exploration_final_eps
    - 0.1
  - - exploration_fraction
    - 0.12
  - - gamma
    - 0.99
  - - gradient_steps
    - -1
  - - learning_rate
    - 0.00063
  - - learning_starts
    - 0
  - - n_timesteps
    - 100000.0
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - dict(net_arch=[256, 256], n_quantiles=25)
  - - target_update_interval
    - 250
  - - train_freq
    - 4
