!!python/object/apply:collections.OrderedDict
- - - n_critic_updates
    - 20
  - - n_envs
    - 2
  - - n_steps
    - 1024
  - - n_timesteps
    - 100000.0
  - - normalize
    - true
  - - policy
    - MlpPolicy
