!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 512
  - - cg_damping
    - 0.001
  - - gae_lambda
    - 0.98
  - - gamma
    - 0.99
  - - learning_rate
    - 0.001
  - - n_critic_updates
    - 20
  - - n_envs
    - 2
  - - n_steps
    - 512
  - - n_timesteps
    - 100000.0
  - - policy
    - MlpPolicy
