!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 64
  - - clip_range
    - 0.2
  - - ent_coef
    - 0.0
  - - gae_lambda
    - 0.95
  - - gamma
    - 0.99
  - - learning_rate
    - 0.0003
  - - n_envs
    - 8
  - - n_epochs
    - 10
  - - n_steps
    - 2048
  - - n_timesteps
    - 2000000.0
  - - policy
    - MlpPolicy
