!!python/object/apply:collections.OrderedDict
- - - buffer_size
    - 200000
  - - gamma
    - 0.99
  - - gradient_steps
    - -1
  - - learning_rate
    - lin_1e-3
  - - learning_starts
    - 10000
  - - n_timesteps
    - 10000000.0
  - - noise_std
    - 0.1
  - - noise_type
    - normal
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - dict(net_arch=[400, 300])
  - - train_freq
    - 1
