!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 256
  - - gamma
    - 0.9999
  - - gradient_steps
    - 1
  - - learning_rate
    - 0.0003
  - - learning_starts
    - 10000
  - - n_timesteps
    - 1000000.0
  - - policy
    - MlpPolicy
  - - train_freq
    - 1
