!!python/object/apply:collections.OrderedDict
- - - gamma
    - 0.9999
  - - gradient_steps
    - 1
  - - learning_starts
    - 10000
  - - n_timesteps
    - 1000000.0
  - - noise_std
    - 0.1
  - - noise_type
    - normal
  - - policy
    - MlpPolicy
  - - train_freq
    - 1
