!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 256
  - - buffer_size
    - 300000
  - - ent_coef
    - auto
  - - env_wrapper
    - sb3_contrib.common.wrappers.TimeFeatureWrapper
  - - gamma
    - 0.98
  - - gradient_steps
    - 64
  - - learning_rate
    - 0.00073
  - - learning_starts
    - 10000
  - - n_timesteps
    - 1000000.0
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - dict(log_std_init=-3, net_arch=[400, 300])
  - - tau
    - 0.02
  - - train_freq
    - 64
  - - use_sde
    - true
