!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 256
  - - gradient_steps
    - 1
  - - learning_rate
    - 0.0003
  - - learning_starts
    - 10000
  - - n_timesteps
    - 2000000.0
  - - policy
    - MlpPolicy
  - - train_freq
    - 1
